version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    restart: unless-stopped
    command: python run.py
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://USERNAME:PASSWORD@HOST:PORT/user_profiles
      - SECRET_KEY=GT6kS1_ascJ2lv8LvL-QIiXGzsBjJvGmFJri5YmKQU6wBamEn3kVjN4YsyTKBTQlH-vz--tLRi-HqToRuHHWeQ==  # Set this to a strong secret key
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_profiles
      POSTGRES_USER: USERNAME
      POSTGRES_PASSWORD: PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U htetaung -d user_profiles"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:

