version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    restart: unless-stopped
    command: python run.py
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      # Point at your AWS RDS instance instead of local Docker DB
      - DATABASE_URL=postgresql://postgres:SHMIgtBBk1zQKYhMSmDX@database-1.c3u0oys8ik2c.eu-west-2.rds.amazonaws.com:5432/<AWS_DB_NAME>
      - SECRET_KEY=${SECRET_KEY:-change-me}
    # No more local db → remove depends_on


