version: "3.8"

services:
  web:
    build: .
    container_name: flask_app
    command: python run.py
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      # Update the DATABASE_URL to point to the db container
      - DATABASE_URL=postgresql://htetaung:password@db:5432/user_profiles
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: user_profiles
      POSTGRES_USER: htetaung
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
